### ISSUE TITLE
Vulnerability in markdown

### ISSUE THREAD

**Issue by markgeraty** [VisionistInc/showdown-xss-filter#4]
The [example here](https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-%28and-how-to-mitigate-it%29#striping-html-tags-is-not-enough) is a vulnerability that still exists using this package.

```
[some text](javascript:alert('xss'))
```

Rather than filtering the HTML before rendering the markdown, we should be filtering it after the markdown is processed, but before it is added to the DOM.

**Comment by markgeraty** [comment]
@tivie Thanks for [the great article](https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-%28and-how-to-mitigate-it%29) ... it looks like, at least in this case, the extension should [be of type](https://github.com/showdownjs/showdown/wiki/Extensions#creating-markdown-extensions) `output` rather than `lang`.

**Comment by tivie** [comment]
Yes, it would make more sense in order to run the library after the output was completely generated.

Our current extension mechanism does not support this (yet?) but ideally your extension should be the last thing to run before the output was return.

Maybe add an extension order or priority? Or an event mediator and trigger some events like "before ouput return"

**Comment by tivie** [comment]
If we implement this i will let you know
